### ISSUE TITLE
Milestone Report 2

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#182]
### Issue Description

Milestone report 2 including deliverables must be prepared.

### Steps
- [x] Executive Summary
    - [x] Summary of project and overall status
    - [x] Description of the basic functionality of your project (can include screen shots)
    - [x] URL of practice app code, the tag, and the URL of your application that was deployed with docker
    - [x] Any information they may need to test our application
    - [x] Instructions for building the application with docker. This should also include a URL which redirects to the swagger page.
    - [x] Meetings notes urls list (related to practice app)
    - [x] Lessons learned: evaluation of tools and processes utilized to manage the team project. Also includes challenges we met as a group.
- [x] #192

### Deadline for the Issue

12.05.2023

**Comment by mehmetSuzer** [comment]
I added the URLs of the meeting notes related to the project to the milestone report

**Comment by Bera0422** [comment]
I wrote about the overall status. It needs to be reviewed and revised if necessary.

**Comment by mehmetSuzer** [comment]
executive summary is completed
