### ISSUE TITLE
Milestone Review

### ISSUE THREAD

**Issue by mehmetSuzer** [bounswe/bounswe2023group9#386]
### Issue Description

A review for milestone report 1 should be written.

### Steps

- [ ] A summary of the project status and any changes that are planned for moving forward
- [ ] A summary of the customer feedback and reflections
- [ ] List and status of deliverables
- [ ] Evaluation of the status of deliverables and its impact on your project plan (reflection)
- [ ] Evaluation of tools and processes you have used to manage your team project
- [ ] The requirements addressed in this milestone

### Deadline for the Issue

03.11.2023 15.00

**Comment by mehmetSuzer** [comment]
I wrote a summary of the project status and our future plans. Those who want to contribute are welcome.

**Comment by Bera0422** [comment]
I wrote about my observations on the audience during the presentation. Everyone is welcome to add their notes.

**Comment by laylaylo** [comment]
I added  _'the requirements addressed in this milestone'_ to report as we prepared it w/ @Brunettow for presentation and reviewed by the team.

**Comment by laylaylo** [comment]
I've added notes I took during the presentation, which include customer feedback.

**Comment by Zulalm** [comment]
I created a list which contains deliverables and their status. Also, I wrote evaluation for the some of the deliverables.

**Comment by mehmetSuzer** [comment]
I wrote the tools that we used up to now.

**Comment by uyduranomer** [comment]
This part of the report is about: Evaluation of Tools and Processes We Have Used to Manage Our Team Project.
The bullet 5 (Flutter) is not a tool to manage the project actually. I think we can remove it from there.

**Comment by laylaylo** [comment]
I agree w/ @uyduranomer. However, I confused about that part. Now, I cannot see much difference from '5- Communication Plan' part.

**Comment by uyduranomer** [comment]
Everything is done, I am closing this issue.
