### ISSUE TITLE
Milestone Report #2 should be prepared.

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#535]
### Issue Description

The report for the Milestone 2 should be prepared. The report should include the following sections:

### Steps

- [ ] A summary of the project status
- [ ] A summary of the customer feedback and reflections
- [ ] Description of any changes since Milestone 1 or planned for the future
- [ ] API endpoints (documentation)
- [ ] Generated unit test reports
- [ ] General test plan for the project
- [ ] The status of the annotation technology
- [ ] Plans for implementing functionalities associated with annotations
- [ ] Individual Contributions

### Deadline for the Issue

01.12.2023 16:59

**Comment by laylaylo** [comment]
Having faced challenges while transferring my individual contributions from Google Docs to the Wiki page for Milestone 1 Report due to numerous update conflicts, I decided to take a different approach for Milestone 2. This time, I opened directly  wiki page for [Milestone Report 2](https://github.com/bounswe/bounswe2023group9/wiki/CmpE451-Customer-Milestone-2-Report) and created the initial draft. I will be adding my contributions directly to this wiki page instead of using Google Docs. I recommend others to follow same approach on contribution part for smoother and timely submission process. For other parts, we can continue to collaborate on Google Docs.

**Comment by Bera0422** [comment]
That's a better idea, thanks. We can use Google Docs only for the text-heavy parts or collaborative editing.
